substitutions:
  _REGION: australia-southeast1
  _REPO: shaunmcn2001
  _SERVICE: vision-backend
  _IMAGE: vision-backend

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    dir: 'services/backend' # Assumes you run the build from the project root
    args: [
      'build',
      '-t', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: [
      'push',
      'australia-southeast1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA'
    ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image australia-southeast1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --timeout=600

images:
  - australia-southeast1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
